Get-ChildItem -Path lib -Recurse -Filter *.dart | ForEach-Object {
    $content = Get-Content $_.FullName -Raw
    $content = $content -replace "import 'package:ionicons/ionicons.dart';\s*", ""
    $content = $content -replace "Ionicons.notifications_outline", "Icons.notifications_none"
    $content = $content -replace "Ionicons.book_outline", "Icons.book_outlined"
    $content = $content -replace "Ionicons.search_outline", "Icons.search"
    $content = $content -replace "Ionicons.school", "Icons.school"
    $content = $content -replace "Ionicons.document", "Icons.description"
    $content = $content -replace "Ionicons.water", "Icons.water_drop"
    $content = $content -replace "Ionicons.sparkles", "Icons.auto_awesome"
    $content = $content -replace "Ionicons.checkmark", "Icons.check"
    $content = $content -replace "Ionicons.flash", "Icons.flash_on"
    $content = $content -replace "Ionicons.checkbox_outline", "Icons.check_box_outline_blank"
    $content = $content -replace "Ionicons.phone_portrait", "Icons.smartphone"
    $content = $content -replace "Ionicons.star", "Icons.star"
    $content = $content -replace "Ionicons.arrow_forward", "Icons.arrow_forward"
    $content = $content -replace "Ionicons.calendar_outline", "Icons.calendar_today"
    $content = $content -replace "Ionicons.calendar", "Icons.calendar_month"
    $content = $content -replace "Ionicons.apps_outline", "Icons.apps"
    $content = $content -replace "Ionicons.apps", "Icons.apps"
    $content = $content -replace "Ionicons.person_outline", "Icons.person_outline"
    $content = $content -replace "Ionicons.person", "Icons.person"
    $content = $content -replace "Ionicons.refresh_outline", "Icons.refresh"
    $content = $content -replace "Ionicons.log_out_outline", "Icons.logout"
    $content = $content -replace "Ionicons.information_circle_outline", "Icons.info_outline"
    $content = $content -replace "Ionicons.time_outline", "Icons.access_time"
    $content = $content -replace "Ionicons.location_outline", "Icons.location_on_outlined"
    $content = $content -replace "Ionicons.location", "Icons.location_on"
    $content = $content -replace "Ionicons.people_outline", "Icons.people_outline"
    $content = $content -replace "Ionicons.grid_outline", "Icons.grid_view"
    $content = $content -replace "Ionicons.alert_circle_outline", "Icons.error_outline"
    $content = $content -replace "Ionicons.shapes_outline", "Icons.category_outlined"
    $content = $content -replace "Ionicons.timer", "Icons.timer"
    $content = $content -replace "Ionicons.happy_outline", "Icons.sentiment_satisfied"
    $content = $content -replace "Ionicons.help_circle_outline", "Icons.help_outline"
    $content = $content -replace "Ionicons.checkmark_circle", "Icons.check_circle"
    Set-Content -Path $_.FullName -Value $content -Encoding UTF8
}
